### PR TITLE
Bootstrap the forms

### PR DESCRIPTION
**Pull request by andrewbelcher**
Before:
profile-before
account-before

### CODE REVIEW

**Comment by andrewbelcher** [comment]
After:
profile-after
account-after

**Comment by andrewbelcher** [comment]
Not sure if we need to do anything with fieldsets, I'm inclined to deal with that as a followup...

**Comment by andrewbelcher** [comment]
Ok, form errors are now fixes as well. This now also includes status messages to tick off when we merge.

**Comment by yanniboi** [comment]
Looks good!

**Pull request merged**
